version: '3.8'

services:
  agent:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RPC_URL=https://api.devnet.solana.com
      - WALLET_PATH=/app/wallet.json
      - TOKEN_DIR=/app/tokens
    volumes:
      - ./wallet.json:/app/wallet.json
      - ./tokens:/app/tokens
    networks:
      - agent-network

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "agent:3000"
    networks:
      - agent-network
    depends_on:
      - agent

networks:
  agent-network:
    driver: bridge
